
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <assert.h>

LIBC_STUB(void, __assert, assert_assert,
    (const char *file, int line, const char *func, const char *expr),
    file, line, func, expr);
