
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <strings.h>

LIBC_STUB(void, bzero, strings_bzero,
    (void *mem, size_t len),
    mem, len);
