
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBC_STUB(int, clock_settime, time_clock_settime,
    (clockid_t aa, const struct timespec *bb),
    aa, bb);
