
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <complex.h>

LIBC_STUB(_Complex double, cpow, complex_cpow,
    (_Complex double aa, _Complex double bb),
    aa, bb);
