
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <complex.h>

LIBC_STUB(_Complex float, cprojf, complex_cprojf,
    (_Complex float aa),
    aa);
