
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdio.h>

LIBC_STUB(int, fputc_unlocked, stdio_fputc_unlocked,
    (int c, FILE *stream),
    c, stream);
