
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBC_STUB(int, fstat, sys_stat_fstat,
    (int fildes, struct stat *buf),
    fildes, buf);
