
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <ftw.h>

LIBC_STUB(int, ftw, ftw_ftw,
    (const char *aa, int (*bb)(const char *, const struct stat *, int), int cc),
    aa, bb, cc);
