
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdio.h>

LIBC_STUB(ssize_t, getdelim, stdio_getdelim,
    (char **lineptr, size_t *n, int delimiter, FILE *stream),
    lineptr, n, delimiter, stream);
