
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <grp.h>

LIBC_STUB(struct group *, getgrgid, grp_getgrgid,
    (gid_t id),
    id);
