
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBC_STUB(int, getopt_long, getopt_getopt_long,
    (int argc, char * const argv[], const char *ostr, const struct option *opts, int *idx),
    argc, argv, ostr, opts, idx);
