
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <sys/resource.h>

LIBC_STUB(int, getrlimit, sys_resource_getrlimit,
    (int aa, struct rlimit *bb),
    aa, bb);
