
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBC_STUB(struct tm *, gmtime_r, time_gmtime_r,
    (const time_t *time, struct tm *tm),
    time, tm);
