
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <wchar.h>

LIBC_STUB(size_t, mbrtowc, wchar_mbrtowc,
    (wchar_t *pwc, const char *s, size_t n, mbstate_t *ps),
    pwc, s, n, ps);
