
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <wchar.h>

LIBC_STUB(int, mbsinit, wchar_mbsinit,
    (const mbstate_t *ps),
    ps);
