
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <wchar.h>

LIBC_STUB(size_t, mbstowcs, wchar_mbstowcs,
    (wchar_t *pwcs, const char *s, size_t n),
    pwcs, s, n);
