
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <string.h>

LIBC_STUB(int, memcmp, string_memcmp,
    (const void *s1, const void *s2, size_t len),
    s1, s2, len);
