
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <string.h>

LIBC_STUB(void *, memmem, string_memmem,
    (const void *aa, size_t bb, const void *cc, size_t dd),
    aa, bb, cc, dd);
