
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <string.h>

LIBC_STUB(void *, memmove, string_memmove,
    (void *dst, const void *src, size_t len),
    dst, src, len);
