
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <langinfo.h>

LIBC_STUB(char *, nl_langinfo, langinfo_nl_langinfo,
    (nl_item aa),
    aa);
