
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <fcntl.h>

LIBC_STUB_VARARGS(int, open, fcntl_open,
    (const char *path, int oflag, ...),
    path, oflag);
