
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdlib.h>

LIBC_STUB(void, qsort, stdlib_qsort,
    (void *base, size_t nel, size_t width, int (*compar)(const void *, const void *)),
    base, nel, width, compar);
