
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdlib.h>

LIBC_STUB(int, rand_r, stdlib_rand_r,
    (unsigned int *seed),
    seed);
