
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdlib.h>

LIBC_STUB(void *, realloc, stdlib_realloc,
    (void *mem, size_t size),
    mem, size);
