
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <unistd.h>

LIBC_STUB(int, setgroups, unistd_setgroups,
    (int aa, const gid_t *bb),
    aa, bb);
