
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <setjmp.h>

LIBC_STUB(int, setjmp, setjmp_setjmp,
    (jmp_buf buf),
    buf);
