
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <locale.h>

LIBC_STUB(char *, setlocale, locale_setlocale,
    (int category, const char *locale),
    category, locale);
