
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <signal.h>

LIBC_STUB(sighandler_t, signal, signal_signal,
    (int sig, sighandler_t func),
    sig, func);
