
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <sys/mount.h>

LIBC_STUB(int, statfs, sys_mount_statfs,
    (const char *aa, struct statfs *bb),
    aa, bb);
