
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <sys/stat.h>

LIBC_STUB(int, stat, sys_stat_stat,
    (const char *path, struct stat *buf),
    path, buf);
