
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <sys/statvfs.h>

LIBC_STUB(int, statvfs, sys_statvfs_statvfs,
    (const char *aa, struct statvfs *bb),
    aa, bb);
