
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <string.h>

LIBC_STUB(size_t, strcspn, string_strcspn,
    (const char *s1, const char *s2),
    s1, s2);
