
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <strings.h>

LIBC_STUB(int, strcasecmp, strings_strcasecmp,
    (const char *s1, const char *s2),
    s1, s2);
