
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED struct PrivFile — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <strings.h>

LIBC_STUB(int, strncasecmp, strings_strncasecmp,
    (const char *s1, const char *s2, size_t len),
    s1, s2, len);
