
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBC_STUB(uintmax_t, strtoumax, inttypes_strtoumax,
    (const char *nptr, char **endptr, int base),
    nptr, endptr, base);
