
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <inttypes.h>

LIBC_STUB(intmax_t, strtoimax, inttypes_strtoimax,
    (const char *nptr, char **endptr, int base),
    nptr, endptr, base);
