
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <sys/stat.h>

LIBC_STUB(mode_t, umask, sys_stat_umask,
    (mode_t cmask),
    cmask);
