
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <utime.h>

LIBC_STUB(int, utime, utime_utime,
    (const char *str, const struct utimbuf *buf),
    str, buf);
