
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdio.h>

LIBC_STUB(int, vfscanf, stdio_vfscanf,
    (FILE *stream, const char *fmt, va_list ap),
    stream, fmt, ap);
