
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <stdio.h>

LIBC_STUB(int, vscanf, stdio_vscanf,
    (const char *fmt, va_list ap),
    fmt, ap);
