
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <sys/wait.h>

LIBC_STUB(pid_t, waitpid, sys_wait_waitpid,
    (pid_t aa, int *bb, int cc),
    aa, bb, cc);
