
/*
** SPDX-License-Identifier: BSD-3-Clause
** Copyright (c) 2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"
#include <unistd.h>

LIBC_STUB(ssize_t, write, unistd_write,
    (int aa, const void *bb, size_t cc),
    aa, bb, cc);
