/* This file is in ISO8859-1 encoding */
static Ihandle *iup_load_lng_spanish( struct libData *data )
{
  return amy_IupSetAtt( data, "SPANISH", amy_IupUser( data ), 
    "IUP_APPLY", "Aplicar", 
    "IUP_ATTENTION", "�Advertencia!", 
    "IUP_BLUE", "&Azul:", 
    "IUP_CANCEL", "Cancelar", 
    "IUP_CONTINUE", "Contin�e", 
    "IUP_COPY", "Copiar", 
    "IUP_COPYTOCLIPBOARD", "Copiar texto para un �rea de transferencia.", 
    "IUP_CREATEFOLDER", "Crear Directorio", 
    "IUP_ERROR", "Error!", 
    "IUP_ERRORFILEOPEN", "Error al abrir el archivo.", 
    "IUP_ERRORFILESAVE", "Error al guardar el archivo.", 
    "IUP_EXIT", "Salir", 
    "IUP_FALSE", "Falso", 
    "IUP_FAMILY", "Familia:", 
    "IUP_FILEISDIR", "El nombre seleccionado es un directorio.", 
    "IUP_FILENOTEXIST", "Archivo inexistente.", 
    "IUP_FILEOVERWRITE", "�Sobrescribir archivo?", 
    "IUP_GETCOLOR", "Selecci�n de Color", 
    "IUP_GREEN", "&Verde:", 
    "IUP_HELP", "Ayuda", 
    "IUP_HUE", "&Matiz:", 
    "IUP_INTENSITY", "&Intensidad:", 
    "IUP_INVALIDDIR", "Directorio inv�lido.", 
    "IUP_LUAERROR", "Error de Lua", 
    "IUP_NAMENEWFOLDER", "Nombre del nuevo directorio:", 
    "IUP_NO", "No", 
    "IUP_OK", "Aceptar", 
    "IUP_OPACITY", "&Opacidad:", 
    "IUP_OPEN", "Abrir", 
    "IUP_PALETTE", "&Paleta:", 
    "IUP_RED", "&Rojo:", 
    "IUP_RESET", "Reiniciar", 
    "IUP_RETRY", "Reintentar", 
    "IUP_SAMPLE", "Ejemplo:", 
    "IUP_SATURATION", "&Saturaci�n:", 
    "IUP_SAVEAS", "Guardar Como", 
    "IUP_SELECTDIR", "Seleccionar Directorio", 
    "IUP_SIZE", "Tama�o:", 
    "IUP_STYLE", "Estilo:", 
    "IUP_TRUE", "Verdadero", 
    "IUP_YES", "Si", NULL );
}
