/* This file is in ISO8859-1 encoding */
static Ihandle *iup_load_lng_portuguese( struct libData *data )
{
  return amy_IupSetAtt( data, "PORTUGUESE", amy_IupUser( data ), 
    "IUP_APPLY", "Aplicar", 
    "IUP_ATTENTION", "Aten��o!", 
    "IUP_BLUE", "&Azul:", 
    "IUP_CANCEL", "Cancelar", 
    "IUP_CONTINUE", "Continuar", 
    "IUP_COPY", "Copiar", 
    "IUP_COPYTOCLIPBOARD", "Copiar texto para a �rea de transfer�ncia.", 
    "IUP_CREATEFOLDER", "Criar Diret�rio", 
    "IUP_ERROR", "Erro!", 
    "IUP_ERRORFILEOPEN", "Falha ao abrir o arquivo.", 
    "IUP_ERRORFILESAVE", "Falha ao salvar o arquivo.", 
    "IUP_EXIT", "Sair", 
    "IUP_FALSE", "Falso", 
    "IUP_FAMILY", "Fam�lia:", 
    "IUP_FILEISDIR", "O nome selecionado � um diret�rio.", 
    "IUP_FILENOTEXIST", "Arquivo inexistente.", 
    "IUP_FILEOVERWRITE", "Sobrescrever arquivo?", 
    "IUP_GETCOLOR", "Sele��o de Cor", 
    "IUP_GREEN", "V&erde:", 
    "IUP_HELP", "Ajuda", 
    "IUP_HUE", "&Matiz:", 
    "IUP_INTENSITY", "&Intensidade:", 
    "IUP_INVALIDDIR", "Diret�rio inv�lido.", 
    "IUP_LUAERROR", "Erro de Lua", 
    "IUP_NAMENEWFOLDER", "Nome do novo diret�rio:", 
    "IUP_NO", "N�o", 
    "IUP_OK", "OK", 
    "IUP_OPACITY", "&Opacidade:", 
    "IUP_OPEN", "Abrir", 
    "IUP_PALETTE", "&Paleta:", 
    "IUP_RED", "&Vermelho:", 
    "IUP_RESET", "Reinicializar", 
    "IUP_RETRY", "Tentar Novamente", 
    "IUP_SAMPLE", "Exemplo:", 
    "IUP_SATURATION", "&Satura��o:", 
    "IUP_SAVEAS", "Salvar Como", 
    "IUP_SELECTDIR", "Selecionar Diret�rio", 
    "IUP_SIZE", "Tamanho:", 
    "IUP_STYLE", "Estilo:", 
    "IUP_TRUE", "Verdadeiro", 
    "IUP_YES", "Sim", NULL );
}
