
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB_VARARGS(U32, RA_Attr_SetParentTags, RA_Attr_SetParentTags,
    (struct RA_Object *obj, ...),
    obj);
