
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(U32, RA_Attr_GetParent, RA_Attr_GetParent,
    (struct RA_Object *obj, U32 id, PTR dst),
    obj, id, dst);
