
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB_VARARGS(struct RA_Class *, RA_Class_FindTags, RA_Class_FindTags,
    (STR name, ...),
    name);
