
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(struct RA_Class *, RA_Class_CreateList, RA_Class_CreateList,
    (struct RA_Class *cl, STR name, U32 size, PTR dis, struct TagItem *list),
    cl, name, size, dis, list);
