
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2026 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(U32, RA_Class_Unlock, RA_Class_Unlock,
    (struct RA_Class *cl),
    cl);
