
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(PTR, RA_Misc_LoadFile_32, RA_Misc_LoadFile_32,
    (STR name, U32 *size),
    name, size);
