
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB_VARARGS(U32, RA_Method_DoSuperNew, RA_Method_DoSuperNew,
    (struct RA_Class *cl, struct RA_Object *obj, ...),
    cl, obj);
