
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(struct RA_Class *, RA_Misc_Plugin_Open, RA_Misc_Plugin_Open,
    (STR name),
    name);
