
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(PTR, RA_Misc_GetTagData, RA_Misc_GetTagData,
    (struct TagItem *tag, U32 id, PTR data),
    tag, id, data);
