
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB(struct RA_Object *, RA_Object_CreateList, RA_Object_CreateList,
    (struct RA_Class *cl, STR name, struct TagItem *list),
    cl, name, list);
