
/*
** SPDX-License-Identifier: BSD-2-Clause
** Copyright (c) 2011-2025 Rene W. Olsen
**
** AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
** Generated by gen_stubs.py
*/

#include "Stub.h"

LIBRA_STUB_VARARGS(struct RA_Object *, RA_Object_CreateTags, RA_Object_CreateTags,
    (struct RA_Class *cl, STR name, ...),
    cl, name);
